### ISSUE TITLE
Shape Inference Warnings for ONNX exports

### ISSUE THREAD

**Issue by glencoe** [es-ude/elastic-ai.creator#12]
Currently we're producing the following warning
```
The shape inference of elasticai.creator::Wrapper type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
```
when exporting to onnx. I do not know atm how to add the shape inference to the symbolic function, but i think we should really do it.

**Comment by miihwi** [comment]
There is this SetType function: https://pytorch.org/docs/stable/onnx.html. But it neither gets rid of the warning, nor can I see an easy way to leverage that

**Comment by RodrigoWIssa** [comment]
There is a setType function: https://pytorch.org/docs/stable/onnx.html. This does not get rid of the warnings, nor can I think on a easy way to leverage that

**Comment by glencoe** [comment]
> There is a setType function: https://pytorch.org/docs/stable/onnx.html. This does not get rid of the warnings, nor can I think on a easy way to leverage that

Damn... that's what i feared. Well, let's keep that open and see when/if someone finds a fix.
