### ISSUE TITLE
Check that tests are executed correctly

### ISSUE THREAD

**Issue by julianhoever** [es-ude/elastic-ai.creator#130]
<img width="573" alt="Screenshot 2022-08-08 at 12 16 22" src="https://user-images.githubusercontent.com/19538187/183874998-639304d8-1433-4442-ab88-0552fede73f6.png">

can you please check whether all tests in the "tests" folder are actually executed in the ci pipeline?... Just stumbled upon this test in "test_derive_data_sets"... obviously it is not a unit test and naturally it takes forever

**Comment by julianhoever** [comment]
@glencoe I have now taken a closer look at which tests are executed in the workflow and on my machine when you start them manually (python3 -m unittest discover --verbose elasticai/creator/tests). Both on my machine and in workflow, the identical 202 tests are executed. Among them is the test you had found and the test passed as well. The funny thing is that when I run the tests via the run button in PyCharm, PyCharm tells me that 240 tests have been run. But even if I test the command PyCharm executes 1:1 like this in my terminal only 202 tests are executed. Maybe this is a bug in PyCharm?

**Comment by glencoe** [comment]
changes in numbers are coming from the one tool counting subtests, while the other doesn't....

Let's remove that test. It is still not terminating on Mac M1 for me. Also testing whether or not you're running out of memory is not something we should do... at least not here.

**Comment by julianhoever** [comment]
The test has already been removed. I will close this issue.
