### ISSUE TITLE
Check GitHub Workflow deprecation warnings

### ISSUE THREAD

**Issue by julianhoever** [es-ude/elastic-ai.creator#170]
During the runtime of our GitHub workflow, we receive the following [deprecation warnings](https://github.com/es-ude/elastic-ai.creator/actions/runs/3454812472):

![deprecation_warnings](https://user-images.githubusercontent.com/19538187/201516680-8b3384f6-a411-4266-9890-bbb3528c825a.png)

I guess we need to fix them soon to make sure our workflows are working as expected.

**Comment by SuperChange001** [comment]
Could you fix this when you have spare hours in the next few weeks? I will focus on end-to-end integration.

**Comment by julianhoever** [comment]
@SuperChange001 Sure. I will have a look at it.

**Comment by julianhoever** [comment]
Done. Only a single deprecation warning left, because the `setup-poetry` action still uses an old Node.js version. It already exists a pull requests for this GitHub Action that just needs to be approved (https://github.com/Gr1N/setup-poetry/pull/32). 

![image](https://user-images.githubusercontent.com/19538187/202860570-fbf2d8c4-d160-4049-9193-00cf6ff67fe4.png)
