### ISSUE TITLE
Fix unittest and integration test workflow

### ISSUE THREAD

**Issue by julianhoever** [es-ude/elastic-ai.creator#182]
The unit test and integration test workflow fails with the following message (https://github.com/es-ude/elastic-ai.creator/actions/runs/3524678266/jobs/5927320471):

![image](https://user-images.githubusercontent.com/19538187/203565600-6b515cd6-bae5-43bd-b243-af45d18e7edd.png)

**Comment by SuperChange001** [comment]
thanks
