### ISSUE TITLE
Tests fail in CI/CD Pipeline due to IO access

### ISSUE THREAD

**Issue by glencoe** [es-ude/elastic-ai.creator#19]
see https://github.com/es-ude/elastic-ai.creator/runs/4764855994?check_suite_focus=true#step:10:147

**Comment by glencoe** [comment]
@AhmadHusein5853 does https://github.com/es-ude/elastic-ai.creator/commit/6167e25f506ebdfef993d04ca87eb8b3381dfaf6 close this issue?

**Comment by AhmadHusein5853** [comment]
yes
