### ISSUE TITLE
Update dependencies in pyproject.toml

### ISSUE THREAD

**Issue by julianhoever** [es-ude/elastic-ai.creator#194]

**Comment by glencoe** [comment]
@julianhoever please check if https://github.com/es-ude/elastic-ai.creator/pull/197/commits/0f78c4bfdddad038bd69b1a92f3b1fba4c5ab9f8
and the current pyproject.toml already do what you had in mind.

**Comment by julianhoever** [comment]
Yes. I think it does what I had in mind. I will close this issue.
