### ISSUE TITLE
The rtl linear layer not producing same result as torch linear implementation

### ISSUE THREAD

**Issue by SuperChange001** [es-ude/elastic-ai.creator#214]
update the linear layer template can fix this problem.

**Comment by julianhoever** [comment]
@SuperChange001 I guess this issue is connected to the pull request #215 which is merged. Can this issue be closed or is there more to do?

**Comment by SuperChange001** [comment]
> @SuperChange001 I guess this issue is connected to the pull request #215 which is merged. Can this issue be closed or is there more to do?

yes, I closed it now
