### ISSUE TITLE
Rewrite and verify LSTM implementation

### ISSUE THREAD

**Issue by julianhoever** [es-ude/elastic-ai.creator#245]
The LSTM implementation is currently completely broken. The `HardTanh` and `HardSigmoid` activations used in the LSTM cell template require bufferless components, which we do not support at the moment. We also need to verify that the LSTM cell and LSTM network templates are filled correctly and that the tests for these components are sufficient to ensure correctness.

**Comment by glencoe** [comment]
lstm implementation has been added again in current develop branch
