### ISSUE TITLE
pytorch api for input_domain.py

### ISSUE THREAD

**Issue by glencoe** [es-ude/elastic-ai.creator#27]
The input_domain module heavily relies on python standard lib and numpy, since we seem to mostly deal with tensors anyway we should try to stick to the pytorch api as much as possible.

**Comment by RodrigoWIssa** [comment]
I think you meant this : https://pytorch.org/docs/stable/generated/torch.cartesian_prod.html . I think we lose flexibility  by using this since it can only deal with 1D iterables  we cannot do [[0,0]], [[1,1]]  and get [[0,0],[1,1]].

**Comment by glencoe** [comment]
allright, thanks for checking it out
